### ISSUE TITLE
Can't execute gist.py

### ISSUE THREAD

**Issue by clwen** [memimo/GIST_Python#1]
Hi there, 

I've downloaded the code and replace the `img_path` to my own image. However, it gives me an error that:
`NameError: global name 'img' is not defined`

Apparently it's because `img` has been commented out in the `test` function. And I saw that the first argument in `gist` function is `image_path` so I changed `print gist(img)` function call to `print gist(img_path)` but it still give me an error at line `items *= arr.shape[ax]`: `IndexError: tuple index out of range`. I've attached the stack trace as image.

I'm kind of stucked here. Any thought? 

Thank you very much for the great library BTW.

![screen shot 2013-09-06 at 11 11 09 am](https://f.cloud.github.com/assets/849046/1096835/a2a5ab00-1706-11e3-9164-51cc80bea544.png)

**Comment by memimo** [comment]
I pushed a fix for the test function. It should be working now.

**Comment by clwen** [comment]
Hey, thanks for replying. I'm still getting the same error (tuple index out of range as previous screenshot). What version of numpy you're using? I'm using numpy 1.8.0 on Mac OSX. Or can you upload the `sea.jpg` so that I can have the same data with you.
